apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - cluster-admins-group.yaml
  # - cluster-admins-rolebinding.yaml
  # - fix-kubeadmin.yaml
  # - htpasswd-cr.yaml
  # - htpasswd-secret.yaml
  - secret-htpasswd.yaml
  - outh-htpasswd.yaml