- name: Install Ollama on OpenShift AI
  hosts: localhost
  vars:
    repo_dir: "{{ lookup('env', 'REPO_DIR') | default(playbook_dir + '/..', true) }}"
  tasks:
    - name: Apply 15-ollama kustomize manifests
      shell: "oc apply -k {{ repo_dir }}/components/15-ollama"
      register: ollama_apply
      retries: 3
      delay: 10
      until: ollama_apply.rc == 0
